import Head from 'next/head'
import Image from 'next/image'
import { useOfflineSync } from '../libs/offline-service.client'
import { useTodo } from '../libs/use-todo'
import styles from '../styles/Home.module.css'


export default function Home() {

  useOfflineSync();
  
  const { todos, addTodo, updateTodo } = useTodo();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* Add todo input  */}
        <input type="text" onKeyDown={(e) => {
          if (e.key === 'Enter') {
            addTodo({
              name: e.currentTarget.value,
              done: false,
              _isDeleted: false,
              lastModified: Date.now(),
            })
            e.currentTarget.value = ''
          }
        }} />

        {todos.map((todo) => (
          
          <div key={todo.cid}>
            <input

              type="checkbox"
              checked={todo.done}
              onChange={() => updateTodo(todo.cid!, {
                done: !todo.done
              })}
            />
            <span>{todo.name}</span>
          </div>
        ))}

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
